# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CodexQuota < Formula
  desc "Terminal account switcher and quota monitor for Codex/OpenCode"
  homepage "https://github.com/deLiseLINO/codex-quota"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deLiseLINO/codex-quota/releases/download/v0.5.1/codex-quota_0.5.1_darwin_amd64.tar.gz"
      sha256 "1ae7f174a6129cfa259566cbe2525e7650bffac316ec6359698d1ca630db94a2"

      define_method(:install) do
        bin.install "cq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deLiseLINO/codex-quota/releases/download/v0.5.1/codex-quota_0.5.1_darwin_arm64.tar.gz"
      sha256 "bf8b143c309ca4d30254753ea89539d1a59fae9c15c5341bd299b489d7b74ecf"

      define_method(:install) do
        bin.install "cq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deLiseLINO/codex-quota/releases/download/v0.5.1/codex-quota_0.5.1_linux_amd64.tar.gz"
      sha256 "31aed405d0526bff74df6552aaa684adab199345fbe14cc28566af7cf5d7f551"
      define_method(:install) do
        bin.install "cq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deLiseLINO/codex-quota/releases/download/v0.5.1/codex-quota_0.5.1_linux_arm64.tar.gz"
      sha256 "e10918f2262d43c2f5c6b701c6369b4530b2cd60b9490f209ee31b04e4a02182"
      define_method(:install) do
        bin.install "cq"
      end
    end
  end

  test do
    system "#{bin}/cq", "--help"
  end
end
