# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CodexQuota < Formula
  desc "Terminal account switcher and quota monitor for Codex/OpenCode"
  homepage "https://github.com/deLiseLINO/codex-quota"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deLiseLINO/codex-quota/releases/download/v0.4.0/codex-quota_0.4.0_darwin_amd64.tar.gz"
      sha256 "995011c4a34a3e5bbeff280c57eb7772b1b9a8aa618a6dec99c19ad0ee26dbeb"

      define_method(:install) do
        bin.install "cq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deLiseLINO/codex-quota/releases/download/v0.4.0/codex-quota_0.4.0_darwin_arm64.tar.gz"
      sha256 "b258f4a56733ca7225cb3003937988e41d5a0c14bbc48a2b018b10fd259256ff"

      define_method(:install) do
        bin.install "cq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deLiseLINO/codex-quota/releases/download/v0.4.0/codex-quota_0.4.0_linux_amd64.tar.gz"
      sha256 "de272a4604d2bec7ebdb61f8629a5e496c2bd4636944dc46c44620bcc60f92e2"
      define_method(:install) do
        bin.install "cq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deLiseLINO/codex-quota/releases/download/v0.4.0/codex-quota_0.4.0_linux_arm64.tar.gz"
      sha256 "afcc252e2976382bce6f6d446720e9fb8609d06582d59e5c83db00dc5062e2ab"
      define_method(:install) do
        bin.install "cq"
      end
    end
  end

  test do
    system "#{bin}/cq", "--help"
  end
end
