# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cq < Formula
  desc "Terminal account switcher and quota monitor for Codex/OpenCode"
  homepage "https://github.com/deLiseLINO/codex-quota"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deLiseLINO/codex-quota/releases/download/v0.1.2/cq_0.1.2_darwin_amd64.tar.gz"
      sha256 "ab6ff9c6ef27d1ea945ed33de06e6f3185ac460fbb7dc2e17a05a236e82020b9"

      define_method(:install) do
        bin.install "cq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deLiseLINO/codex-quota/releases/download/v0.1.2/cq_0.1.2_darwin_arm64.tar.gz"
      sha256 "cfd7c48720b220aedf3dcf4ce66b7b8c10775466692e239feebc3fed76087a21"

      define_method(:install) do
        bin.install "cq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deLiseLINO/codex-quota/releases/download/v0.1.2/cq_0.1.2_linux_amd64.tar.gz"
      sha256 "88b247a03e54e4b44652a1800169b3261925d3fbe65ca4c43c38784b2f2c297d"
      define_method(:install) do
        bin.install "cq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deLiseLINO/codex-quota/releases/download/v0.1.2/cq_0.1.2_linux_arm64.tar.gz"
      sha256 "0750deed60d5e93198d3664f4faa62b37d6840dba4bfd438f3c1c9bfc4577017"
      define_method(:install) do
        bin.install "cq"
      end
    end
  end

  test do
    system "#{bin}/cq", "--help"
  end
end
